DISC

--CONN falcon/&Falcon_Password_or_Type_falc@&Database_Name;
CONN falcon/&Password_type_falc@//&HOSTNAME:&PORT/&DATABASE_NAME;

BEGIN
  DBMS_SCHEDULER.drop_job (job_name => 'PROJECT_STATUS_OVERDUE');
END;
/
BEGIN
  DBMS_SCHEDULER.drop_job (job_name => 'PROJECT_NOTIFY_MAILING');
END;
/
BEGIN
  DBMS_SCHEDULER.drop_job (job_name => 'PROJECT_AUTOMATED_CLOSING');
END;
/
BEGIN
  DBMS_SCHEDULER.drop_job (job_name => 'NOTIFY_PROJECT_NO_TASK');
END;
/
BEGIN
  DBMS_SCHEDULER.drop_job (job_name => 'SIX_MONTHS_STATUS');
END;
/
BEGIN
  DBMS_SCHEDULER.drop_job (job_name => 'JOB_CHECKER_DELETED');
END;
/
BEGIN
DBMS_SCHEDULER.DROP_JOB(JOB_NAME => 'MY_JOB');
END;
/
DROP TRIGGER project_halt;
DROP TRIGGER project_remove;
DROP TRIGGER project_task_approval;
DROP TRIGGER project_team_member_add;
DROP TRIGGER project_threshold;
DROP TRIGGER first_admin;
DROP TRIGGER project_role_strict;
DROP TRIGGER project_auth_placement;
DROP PROCEDURE project_activity;
DROP PROCEDURE project_closing;
DROP PROCEDURE project_mail_to_assignee;
DROP PROCEDURE project_overdue_notify;
DROP PROCEDURE project_progress;
DROP PROCEDURE project_status;
DROP FUNCTION GET_IDENTITY;
DROP FUNCTION hr_duration;
DROP FUNCTION METE;
DROP FUNCTION time_spell;
DROP FUNCTION encrypto;
DROP FUNCTION decrypto;
DROP FUNCTION BLOB_TO_CLOB;
DROP FUNCTION BINARY_TO_CLOB;
DROP VIEW TOTAL_PERM;


DELETE FROM PROJECT_STORES;
DELETE FROM PROJECT_ATTACHMENTS;
DELETE FROM USER_TASKS;
DELETE FROM PROJECT_DETAILS;
DELETE FROM PROJECTS;
DELETE FROM TEAM_MEMBERS;
DELETE FROM USERS_ROLE;
DELETE FROM TEAMS;
DELETE FROM ROLE_TABLES;
DELETE FROM USER_TABLES;
DELETE FROM PROGRESS_TRACKS;
DELETE FROM PROGRESS;
DELETE FROM CHECK_JOBS;

ALTER TABLE USER_TABLES DROP CONSTRAINT TASK_TO_USERFK;
DROP TABLE PROJECT_STORES PURGE;
DROP TABLE PROJECT_ATTACHMENTS PURGE;
DROP TABLE USER_TASKS PURGE;
DROP TABLE PROJECT_DETAILS PURGE;
DROP TABLE PROJECTS PURGE;
DROP TABLE TEAM_MEMBERS PURGE;
DROP TABLE USERS_ROLE PURGE;
DROP TABLE TEAMS PURGE;
DROP TABLE ROLE_TABLES PURGE;
DROP TABLE USER_TABLES PURGE;
DROP TABLE PROGRESS_TRACKS PURGE;
DROP TABLE PROGRESS PURGE;
DROP TABLE CHECK_JOBS PURGE;


DISC;

CONN sys/&SYS_PASSWORD@//&HOSTNAME:&PORT/&DATABASE_NAME as sysdba;

DROP USER falcon CASCADE;